<a href="https://colab.research.google.com/github/PrathamGarg28/big_data/blob/main/labeval_1mca2_202301044.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#sorted array
#indices of sorted array
#4 smallest elements
#5 largest elements
import numpy as np
array=np.array([10,52,62,16,16,54,453])
sortedArr=np.sort(array)
indices=np.argsort(array)
smallest=sortedArr[:4]
largest=sortedArr[2:]
print("1> Base Array------")
print(array)
print("2> Sorted Array------")
print(sortedArr)
print("3> Indices of  Array------")
print(indices)
print("4> 4 Smallest Elements------")
print(smallest)
print("5> 5 Largest Elements------")
print(largest)

1> Base Array------
[ 10  52  62  16  16  54 453]
2> Sorted Array------
[ 10  16  16  52  54  62 453]
3> Indices of  Array------
[0 3 4 1 5 2 6]
4> 4 Smallest Elements------
[10 16 16 52]
5> 5 Largest Elements------
[ 16  52  54  62 453]
